# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='modified',
        ),
        migrations.AddField(
            model_name='dialog',
            name='opponent_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dialog',
            name='owner_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dialog',
            name='secret_key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
