# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0002_auto_20170817_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
