# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0003_auto_20170821_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dialog opponent'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfDialogs', to=settings.AUTH_USER_MODEL, verbose_name='Dialog owner'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
