CONNECT_PATH_REGEX = r'^\/chat\/(?P<owner_id>\d{1,})\/(?P<opponent_id>\d{1,})$'
DIALOG_TOKEN_EXPIRY_MINUTES = 10
PMS_PER_QUERY = 20
EXPIRED_TOKEN_ERR_TYPE = 'EXPIRED_CONVERSATION_TOKEN'
AUTHORIZATION_ERR_TYPE = 'NO_AUTHORIZATION'
NOT_FOUND_ERR_TYPE = 'NOT_FOUND'
VALIDATION_ERR_TYPE = 'VALIDATION_ERROR'
WARNING_ERR_TYPE = 'WARNING'
