# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 08:21
from __future__ import unicode_literals

import challenges.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0038_auto_20170605_0809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10), challenges.validators.PossibleFloatDigitValidator(['0', '5'])])),
                ('languages', models.ManyToManyField(to='challenges.Language')),
                ('teachers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
