# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('video_link_1', models.CharField(default='', max_length=100)),
                ('video_link_2', models.CharField(default='', max_length=100)),
                ('video_link_3', models.CharField(default='', max_length=100)),
                ('video_link_4', models.CharField(default='', max_length=100)),
                ('video_link_5', models.CharField(default='', max_length=100)),
                ('intro', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=3000)),
                ('annexation', models.CharField(max_length=3000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.Course')),
            ],
        ),
    ]
