# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20170620_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_mandatory',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.Lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworktaskdescription',
            name='constraints',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homeworktaskdescription',
            name='content',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='homeworktaskdescription',
            name='explanation',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homeworktaskdescription',
            name='input_format',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='homeworktaskdescription',
            name='output_format',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homeworktaskdescription',
            name='sample_input',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='homeworktaskdescription',
            name='sample_output',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
