# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_usercourseprogress_userlessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_under_construction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_under_construction',
            field=models.BooleanField(default=True),
        ),
    ]
