# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20170621_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkTaskTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file_path', models.CharField(max_length=150)),
                ('output_file_path', models.CharField(max_length=150)),
                ('consecutive_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='test_case_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeworktasktest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.HomeworkTask'),
        ),
    ]
