# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20170622_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworktask',
            name='is_under_construction',
            field=models.BooleanField(default=True),
        ),
    ]
