# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0038_auto_20170605_0809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0008_homeworktask_is_under_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4000)),
                ('celery_task_id', models.CharField(max_length=100)),
                ('is_solved', models.BooleanField(default=False)),
                ('result_score', models.IntegerField(default=0, verbose_name='The points from the challenge')),
                ('grading_is_pending', models.BooleanField(default=True)),
                ('has_compiled', models.BooleanField(default=True)),
                ('compile_error_message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timed_out', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Language')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.HomeworkTask')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', through='education.UserCourseProgress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='education.Course'),
        ),
    ]
