# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_remove_tasksubmission_result_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=1000)),
                ('traceback', models.CharField(max_length=2000)),
                ('error_message', models.CharField(max_length=100)),
                ('timed_out', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.TaskSubmission')),
            ],
        ),
    ]
