# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0011_tasktestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='main_teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
