# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_newsfeeditemcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsfeedLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('newsfeed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.NewsfeedItem')),
            ],
        ),
    ]
