# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_newsfeedlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeeditemcomment',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.NewsfeedItemComment'),
        ),
    ]
