# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=60),
        ),
    ]
