# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20170823_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('updated_at',)},
        ),
    ]
