# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-07 18:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20170823_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('updated_at',)},
        ),
        migrations.AlterField(
            model_name='newsfeeditem',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
