# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_confirm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
