# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('rating', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
