# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
