# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='0.00s', max_length=5)),
                ('success', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Submission')),
            ],
        ),
    ]
