# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_test_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='task_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
