# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_challenge_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
                ('input_format', models.CharField(max_length=500)),
                ('output_format', models.CharField(max_length=1000)),
                ('constraints', models.CharField(max_length=1000)),
                ('sample_input', models.CharField(max_length=1000)),
                ('sample_output', models.CharField(max_length=1000)),
                ('explanation', models.CharField(max_length=1000)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='challenges.ChallengeDescription')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='challenges.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='challenges.ChallengeCategory'),
        ),
    ]
