# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_auto_20170222_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengedescription',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenges.ChallengeDescription'),
            preserve_default=False,
        ),
    ]
