# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0017_auto_20170223_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compile_error_message',
            field=models.CharField(default=True, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='compiled',
            field=models.BooleanField(default=True),
        ),
    ]
