# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0019_auto_20170310_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='supported_languages',
            field=models.ManyToManyField(to='challenges.Language'),
        ),
    ]
