# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='test_file_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
