# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_submission_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='test_case_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
