# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challenge_test_case_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='traceback',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
