# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20170221_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='error_message',
            field=models.CharField(default='whatever', max_length=100),
            preserve_default=False,
        ),
    ]
