# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20170221_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('meta_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.ChallengeCategory')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
