# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20170222_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenges.SubCategory'),
            preserve_default=False,
        ),
    ]
