# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_submission_created_at'),
    ]

    operations = [
        migrations.RenameModel('ChallengeCategory', 'MainCategory')
    ]
