# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 06:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0020_challenge_supported_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='rating',
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.FloatField(default=1.5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
