# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0021_auto_20170520_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='rating',
            new_name='difficulty',
        ),
    ]
