# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 06:34
from __future__ import unicode_literals

import challenges.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0022_auto_20170522_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10), challenges.validators.PossibleFloatDigitValidator(['0', '5'])]),
        ),
    ]
