# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0023_language_default_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Submission')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submissionvote',
            unique_together=set([('submission', 'author')]),
        ),
    ]
