# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0024_auto_20170524_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submissionvote',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='challenges.Submission'),
        ),
    ]
