# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0025_auto_20170526_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
