# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('challenges', '0027_auto_20170530_0822'), ('challenges', '0028_auto_20170530_0823'), ('challenges', '0029_auto_20170530_0824')]

    dependencies = [
        ('challenges', '0026_submission_timed_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='elapsed_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
