# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0027_auto_20170530_0822_squashed_0029_auto_20170530_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='elapsed_seconds',
            new_name='elapsed_seconds',
        ),
    ]
