# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('challenges', '0029_subcategory_max_score'), ('challenges', '0030_auto_20170602_0913')]

    dependencies = [
        ('challenges', '0028_auto_20170530_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='The maximum score from all the challenges in this subcategory'),
        ),
    ]
