# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0029_subcategory_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='The maximum score from all the challenges in this subcategory'),
        ),
    ]
