# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0029_subcategory_max_score_squashed_0030_auto_20170602_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubcategoryProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(default=0, verbose_name='The score that the user has accumulated for this subcategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usersubcategoryprogress',
            unique_together=set([('user', 'subcategory')]),
        ),
    ]
