# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0037_auto_20170605_0756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubcategoryprogress',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usersubcategoryprogress',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='usersubcategoryprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='usersubcategoryproficiency',
            name='user_score',
            field=models.IntegerField(default=0, verbose_name='The score that the user has accumulated for this subcategory'),
        ),
        migrations.DeleteModel(
            name='UserSubcategoryProgress',
        ),
    ]
