# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0038_auto_20170605_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Language'),
        ),
    ]
