# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0040_submissioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
