# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0045_usersolvedchallenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.SubCategory'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.ChallengeDescription'),
        ),
        migrations.AlterField(
            model_name='challengecomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='challenges.MainCategory'),
        ),
        migrations.AlterField(
            model_name='subcategoryproficiencyaward',
            name='proficiency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.Proficiency'),
        ),
        migrations.AlterField(
            model_name='subcategoryproficiencyaward',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.SubCategory'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.Language'),
        ),
        migrations.AlterField(
            model_name='submissioncomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissionvote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersubcategoryproficiency',
            name='proficiency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.Proficiency'),
        ),
        migrations.AlterField(
            model_name='usersubcategoryproficiency',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.SubCategory'),
        ),
    ]
