# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170617_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_followed',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
