# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_users_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
