# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='submission_count',
            field=models.IntegerField(default=0),
        ),
    ]
