# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 19:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_notification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=25)),
                ('school', models.CharField(max_length=100)),
                ('school_major', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('job_company', models.CharField(max_length=30)),
                ('personal_website', models.CharField(max_length=100)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=5)),
                ('facebook_link', models.CharField(max_length=100)),
                ('twitter_link', models.CharField(max_length=100)),
                ('github_link', models.CharField(max_length=100)),
                ('linkedin_link', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
