# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 17:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171028_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=35), size=5),
        ),
    ]
